apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverless-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverless-app
  template:
    metadata:
      labels:
        app: serverless-app
    spec:
      containers:
      - name: serveless-app
        image: lucasmsp/serverless:redis
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: pyfile-config
          mountPath: /app/handle.py
          readOnly: true
        env:
        - name: REDIS_HOST
          value: "192.168.121.66"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_INPUT_KEY
          value: "metrics"
        - name: REDIS_OUTPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: outputkey
              key: REDIS_OUTPUT_KEY
      volumes:
        - name: pyfile-config
          configMap:
            name: pyfile
        - name: outputkey-config
          configMap:
            name: outputkey
